# Generated by Django 5.1.4 on 2025-01-06 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("items", "0001_initial"),
        ("supplier", "0001_initial"),
        ("type", "0001_initial"),
        ("unit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IGP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("igp_number", models.CharField(max_length=20, unique=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "vehicle_number",
                    models.CharField(blank=True, default="Nill", max_length=20),
                ),
                (
                    "vehicle_type",
                    models.CharField(blank=True, default="Nill", max_length=50),
                ),
                (
                    "driver_name",
                    models.CharField(blank=True, default="Nill", max_length=50),
                ),
                (
                    "driver_contact",
                    models.CharField(blank=True, default="Nill", max_length=15),
                ),
                (
                    "address",
                    models.CharField(default="supplier address", max_length=100),
                ),
                (
                    "messer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplier",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="type.type"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IGPItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "igp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="igp.igp"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.item"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="unit.unit"
                    ),
                ),
            ],
        ),
    ]
