# Generated by Django 5.1.4 on 2024-12-26 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("igp", "0004_alter_igp_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="igp",
            name="description",
        ),
        migrations.RemoveField(
            model_name="igp",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="igp",
            name="sr_no",
        ),
        migrations.RemoveField(
            model_name="igp",
            name="unit",
        ),
        migrations.AddField(
            model_name="igp",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="igp",
            name="driver_cnic",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="igp",
            name="driver_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="igp",
            name="vehicle_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="igp",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mazda", "Mazda"),
                    ("toyota", "Toyota"),
                    ("suzuki", "Suzuki"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="igp",
            name="igp_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="igp",
            name="messer",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="igp",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="igp",
            name="type",
            field=models.CharField(
                choices=[("Raw Material", "Raw Material"), ("Inward", "Inward")],
                default="Inward",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=20)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "igp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="igp.igp",
                    ),
                ),
            ],
        ),
    ]
