# Generated by Django 5.1.4 on 2024-12-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("igp", "0005_remove_igp_description_remove_igp_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="igp",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("mazda", "Mazda"),
                    ("toyota", "Toyota"),
                    ("suzuki", "Suzuki"),
                ],
                default="mazda",
                max_length=20,
            ),
        ),
    ]
